config/routes.rb
Rails.application.routes.draw do
scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, controllers: { registrations: 'users/registrations' }

    devise_scope :user do  
      get '/users/sign_out' => 'devise/sessions#destroy'     
    end

    resources :dotfiles

    resources :dotfiles do
      member do
        patch :vote
        patch :bookmark
      end
    end

    root 'home#index'
    get 'bookmarks/index'

    resources :users, only: [:show]
  end
end

app/models/dotfile.rb
class Dotfile < ApplicationRecord
  has_one_attached :file
  belongs_to :user

  validates :title, presence: true, format: { with: /\A[a-zA-Z0-9_.\s]+\Z/ }
  validates :description, presence: true, format: { with: /\A[a-zA-Z0-9_.\s]+\Z/ }
  validates :config_type, presence: true, format: { with: /\A[a-zA-Z_.\s]+\Z/ }
  validates :file, presence: true

  validate :allowed_file_extension
  
  acts_as_votable

  def bookmark!(user)
    if user.voted_up_on? self, vote_scope: "bookmark"
      unvote_by user, vote_scope: "bookmark"
    else
      upvote_by user, vote_scope: "bookmark"
    end
  end

  def upvote!(user)
    if user.voted_up_on? self, vote_scope: "like"
      unvote_by user, vote_scope: "like"
    else
      upvote_by user, vote_scope: "like"
    end
  end

  def downvote!(user)
    if user.voted_down_on? self, vote_scope: "like"
      unvote_by user, vote_scope: "like"
    else
      downvote_by user, vote_scope: "like"
    end
  end

  def allowed_file_extension
    allowed_extensions = %w[fish lua conf]
    if file.present? && !allowed_extensions.include?(File.extname(file.filename.to_s).delete("."))
      errors.add(:file, I18n.t('errors.invalid_extension'))
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    ["title", "description", "config_type", "username"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end
end

app/controllers/dotfiles_controller.rb
# frozen_string_literal: true

# Controller for dotfiles logic
class DotfilesController < ApplicationController
  include Pagy::Backend

  before_action :set_dotfile, only: %i[show edit update destroy vote bookmark]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]

  # GET /dotfiles or /dotfiles.json
  def index
    search_params = params.permit(:format, :page, :commit, :locale,
                                  q: %i[title_or_description_or_config_type_or_user_username_cont config_type_eq s])
    @q = Dotfile.ransack(search_params[:q])
    order_by = get_order_(search_params)
    dotfiles = @q.result(distinct: true).order(order_by => :desc)
    @dotfiles_pagy, @dotfiles = pagy(dotfiles, items: 2)
  rescue Pagy::OverflowError
    redirect_to dotfiles_path(page: 1)
  end

  def get_order_(search_params)
    if !search_params[:q].nil? && !search_params[:q][:s].nil?
      order_by = search_params[:q][:s].split[0]
      order_by = (order_by == 'created_at' ? :created_at : :cached_weighted_like_score)
    else
      order_by = :cached_weighted_like_score
    end
    order_by
  end

  def bookmark
    @dotfile.bookmark!(current_user)
    respond_to do |format|
      format.html do
        redirect_to @dotfile
      end
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          @dotfile, partial: 'dotfiles/dotfile',
                    locals: { dotfile: @dotfile, show_config: params[:show_config] }
        )
      end
    end
  end

  def vote
    case params[:type]
    when 'upvote'
      @dotfile.upvote!(current_user)
    when 'downvote'
      @dotfile.downvote!(current_user)
    else
      return redirect_to request.url, alert: 'no such vote type'
    end
    respond_to do |format|
      format.html do
        redirect_to @dotfile
      end
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(@dotfile, partial: 'dotfiles/dotfile',
                                                            locals: { dotfile: @dotfile, show_config: params[:show_config] })
      end
    end
  end

  # GET /dotfiles/1 or /dotfiles/1.json
  def show; end

  # GET /dotfiles/new
  def new
    @dotfile = current_user.dotfiles.build
  end

  # GET /dotfiles/1/edit
  def edit; end

  # POST /dotfiles or /dotfiles.json
  def create
    @dotfile = current_user.dotfiles.build(dotfile_params)

    respond_to do |format|
      if @dotfile.save
        format.html { redirect_to dotfile_url(@dotfile), notice: I18n.t('notices.create_dotfile') }
        format.json { render :show, status: :created, location: @dotfile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dotfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dotfiles/1 or /dotfiles/1.json
  def update
    respond_to do |format|
      if @dotfile.update(dotfile_params)
        format.html { redirect_to dotfile_url(@dotfile), notice: I18n.t('notices.update_dotfile') }
        format.json { render :show, status: :ok, location: @dotfile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dotfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dotfiles/1 or /dotfiles/1.json
  def destroy
    @dotfile.destroy!

    respond_to do |format|
      format.html { redirect_to dotfiles_url, notice: I18n.t('notices.destroy_dotfile') }
      format.json { head :no_content }
    end
  end

  def correct_user
    @dotfile = current_user.dotfiles.find_by(id: params[:id])
    redirect_to dotfiles_path, notice: I18n.t('notices.not_authorized_to_edit') if @dotfile.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_dotfile
    @dotfile = Dotfile.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def dotfile_params
    params.require(:dotfile).permit(:title, :description, :config_type, :file, :user_id)
  end
end

app/helpers/dotfiles_helper.rb
module DotfilesHelper
  def upvote_label(message, user)
    label_text = if user.voted_up_on? message, vote_scope: "like"
                    "UNvote"
                  else
                    "UPvote"
                  end
    tag.span do
      "#{message.cached_scoped_like_votes_up} #{label_text}"
    end
  end

  def downvote_label(message, user)
    label_text = if user.voted_down_on? message, vote_scope: "like"
                    "UNvote"
                  else
                    "DOWNvote"
                  end
    tag.span do
      "#{message.cached_scoped_like_votes_down} #{label_text}"
    end
  end

  def upvote_label_styles(dotfile, user)
    if user&.voted_up_on? dotfile, vote_scope: "like"
      "background-color: #e9ecef;"
    end
  end

  def downvote_label_styles(dotfile, user)
    if user&.voted_down_on? dotfile, vote_scope: "like"
      "background-color: #e9ecef;"
    end
  end

  def bookmark_label_styles(message, user)
    if user.voted_up_on? message, vote_scope: "bookmark"
      "background-color: #e9ecef;"
    end
  end


  def bookmark_label_styles(dotfile, user)
    if user&.voted_up_on? dotfile, vote_scope: "bookmark"
      "background-color: #e9ecef;"
    end
  end
end

app/views/dotfiles/_dotfile.html.erb
<div id="<%= dom_id dotfile %>" class="card shadow-sm">
  <div class="card-header">
    <div>
      <div style="display: inline-block; width: 49.5%">
        <%= link_to "#{dotfile.title}", dotfile, class: "text-decoration-none fw-bold fs-4" %> <span style="margin-left: 5px"><%= link_to "@#{dotfile.user.username}", dotfile.user, class: "text-decoration-none text-secondary" %></span>
      </div>
      <div style="display: inline-block; text-align: right; width: 49.5%; color: grey">
        <%= dotfile.config_type %>
      </div>
    </div>
  </div>

  <div class="card-body">
    <p><%= dotfile.description %></p><br>

    <div style="display: flex; flex-direction: row">
      <%= button_to "", vote_dotfile_path(dotfile, type: :upvote, show_config: defined?(show_config) && show_config), method: :patch, style: upvote_label_styles(dotfile, current_user), class: "bi bi-arrow-up btn btn-sm btn-light me-1" %>
      <%= dotfile.cached_weighted_like_score %>
      <%= button_to "", vote_dotfile_path(dotfile, type: :downvote, show_config: defined?(show_config) && show_config), method: :patch, style: downvote_label_styles(dotfile, current_user), class: "bi bi-arrow-down btn btn-sm btn-light ms-1" %>
      
      <%= button_to "", bookmark_dotfile_path(dotfile, show_config: defined?(show_config) && show_config), method: :patch, style: bookmark_label_styles(dotfile, current_user), class: "bi bi-bookmark btn btn-sm btn-light ms-5" %>
      <%= link_to "", dotfile.file, style: "float: right", class: "bi bi-download btn btn-sm btn-light ms-1" %>
              
      <% if dotfile.user == current_user %>
        <%= link_to "", edit_dotfile_path(dotfile), class: "bi bi-pencil-square btn btn-sm btn-light ms-5" %>
      <% end %>
    </div>

    <% if defined?(show_config) && show_config %>
      <br>
      <button id="hide-button" class="btn btn-outline-secondary btn-sm">Hide</button>
      <div id="hide-target">
        <br>
        <pre class="prettyprint form-control" style="background-color: #f8f8f8; border: 1px solid #d3d3d3; padding: 10px; font-size: 14px"><code class="lang-sh" style=""><%= raw(dotfile.file.download) %></code></pre> 
      </div>
    <% end %>
  </div>
</div>
<%= javascript_include_tag 'hide_dotfile' %>

app/views/dotfiles/_form.html.erb
<%= render 'layouts/header' %>
<div class="container justify-content-center mt-5" style="width: 450px; min-height: 100vh">
  <div class="card shadow-sm">
    <% if defined?(purpose) && purpose == "new" %>
      <h4 class="card-header"><%= t('forms.creating_dotfile.title') %></h4>
    <% elsif defined?(purpose) && purpose == "edit" %>
      <h4 class="card-header"><%= t('forms.editing_dotfile.title') %></h4>
    <% end %>
    <div class="card-body">
      <%= form_with(model: dotfile) do |form| %>
        <% if dotfile.errors.any? %>
          <div class="alert alert-danger">
            <ul>
              <% dotfile.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="container">
          <div class="mb-3">
            <%= form.label :title, class: "form-label" %>
            <%= form.text_field :title, class: "form-control", id: "title", required: true %>
          </div>

          <div class="mb-3">
            <%= form.label :description, class: "form-label" %>
            <%= form.text_area :description, class: "form-control", id: "description", required: true %>
          </div>

          <div class="mb-3">
            <%= form.label :config_type, class: "form-label" %>
            <%= form.select :config_type, options_for_select([
              ["tmux", "tmux"],
              ["nvim", "nvim"],
              ["fish", "fish"],
              ["nginx", "nginx"],
            ], selected: @dotfile.config_type), {}, {class: "form-select form-select", id: "config_type", required: true} %>
          </div>

          <div class="mb-3">
            <%= form.label :file, class: "form-label" %>
            <%= form.file_field :file, class: "form-control", id: "file", type: "file" %>
          </div>

          <div class="mb-3">
            <%= form.number_field :user_id, id: :dotfile_user_id, value: current_user.id, type: :hidden %>
          </div>

          <br>

          <div class="d-flex justify-content-center">
            <%= form.submit class: "btn btn-primary shadow-sm", style: "width: 100%", id: "create_button" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <% if defined?(purpose) && purpose == "edit" %>
    <div>
      <%= button_to t('forms.editing_dotfile.delete'), @dotfile, class: "btn btn-outline-danger mt-3", data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete %>
    </div>
  <% end %>
</div>
<%= render 'layouts/footer' %>

app/views/dotfiles/edit.html.erb
<%= render "form", dotfile: @dotfile, purpose: "edit" %>

app/views/dotfiles/index.html.erb
<%= render 'layouts/header' %>
<div class="container d-flex justify-content-center mt-5" style="width: 100%; weight: 100%; min-height: 100vh">
  <div style="width: 70%">
      <h1><%= t('header.explore') %></h1><br>

      <% if defined?(notice) && (not notice.nil?) %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
        <br>
      <% end %>
      
      <div class="form-inline">
        <%= search_form_for @q, url: dotfiles_path do |f| %>
          <div>
            <%= f.label :title_or_description_or_config_type_or_user_username_cont, t('forms.searching.search'), class: 'sr-only' %>
            <%= f.search_field :title_or_description_or_config_type_or_user_username_cont,
              class: 'form-control',
              autofocus: true,
              autocomplete: 'off',
              placeholder: t('forms.searching.search_placeholder') %>
          </div>

          <div class="mt-3">
            <%= f.label :config_type_eq, t('forms.searching.config_type'), class: 'sr-only' %>
            <%= f.select :config_type_eq,
              Dotfile.pluck(:config_type).uniq,
              { include_blank: true },
              class: 'form-select',
              style: 'width: 200px;',
              onchange: 'this.form.submit();'
            %>
          </div>

          <div>
            <div style="display: inline-block; width: 49.5%">
              <%= f.submit t('forms.searching.search_button'), class: 'btn btn-primary mt-3 shadow-sm' %>
            </div>
            <div style="display: inline-block; text-align: right; width: 49.5%">
              <%= t('forms.searching.order_by') %>:
              <%= sort_link(@q, :cached_weighted_like_score, t('forms.searching.votes'), default_order: :desc, hide_indicator: true, class: "link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover", style: "margin-left: 10px") %>
              <%= sort_link(@q, :created_at, t('forms.searching.recent'), default_order: :desc, hide_indicator: true, class: "link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover", style: "margin-left: 10px") %>
            </div>
          </div>
        <% end %>
      </div>

      <br><br>

      <div id="dotfiles">
        <% @dotfiles.each do |dotfile| %>
          <div class="mt-3">
            <%= render dotfile %>
          </div>
        <% end %>
      </div>

      <% if @dotfiles_pagy.count > @dotfiles_pagy.items %>
        <div class="d-flex justify-content-center mt-5" style="width: 100%; weight: 100%">
          <%== pagy_bootstrap_nav(@dotfiles_pagy) %>
        </div>
      <% end %> 
  </div>
</div>
<%= render 'layouts/footer' %>

app/views/dotfiles/new.html.erb
<%= render "form", dotfile: @dotfile, purpose: "new" %>

app/views/dotfiles/show.html.erb
<%= render 'layouts/header' %>
<div class="container d-flex justify-content-center mt-5" style="width: 100%; weight: 100%; min-height: 100vh">
  <div style="width: 70%">
    <% if defined?(notice) && (not notice.nil?) %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
      <br>
    <% end %>

    <%= render @dotfile, show_config: true %> 
  </div>
</div>
<%= render 'layouts/footer' %>