config/routes.rb
Rails.application.routes.draw do
scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, controllers: { registrations: 'users/registrations' }

    devise_scope :user do  
      get '/users/sign_out' => 'devise/sessions#destroy'     
    end

    resources :dotfiles

    resources :dotfiles do
      member do
        patch :vote
        patch :bookmark
      end
    end

    root 'home#index'
    get 'bookmarks/index'

    resources :users, only: [:show]
  end
end

app/views/layouts/_footer.html.erb
<footer class="py-3 my-4 mt-1">
  <ul class="nav justify-content-center border-bottom pb-3 mb-3" style="margin-top: 30px">
    <li class="nav-item"><%= link_to t('global.title'), root_path, class: "nav-link px-2 text-muted", style: "font-weight: 600" %></li>
    <li class="nav-item"><%= link_to t('header.explore'), dotfiles_path, class: "nav-link px-2 text-muted" %></li>
    <% if user_signed_in? %> 
      <li class="nav-item"><%= link_to t('header.saved'), bookmarks_index_path, class: "nav-link px-2 text-muted" %></li>
    <% end %>
  </ul>
  <p class="text-center text-muted"><%= t('global.copyright') %></p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary shadow-sm">
  <div class="container-fluid">
    <%= link_to t('global.title'), root_path, class: "navbar-brand", style: "font-weight: 600" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0"> 
        <li class="nav-item">
          <%= link_to t('header.explore'), dotfiles_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %> 
          <li class="nav-item">
            <%= link_to t('header.saved'), bookmarks_index_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t('header.create'), new_dotfile_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <div style="margin-right: 20px">
        <%= link_to 'en', dotfiles_path(locale: :en), class: "link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %>
        <span class="text-secondary"> | </span><%= link_to 'ру', dotfiles_path(locale: :ru), class: "link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %>
      </div>
      <% if user_signed_in? %> 
        <a class="nav-link dropdown-toggle me-2 text-secondary" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= t('header.profile.title') %>
        </a>
        <ul class="dropdown-menu dropdown-menu-end me-2" aria-labelledby="navbarDropdown">
          <li><%= link_to t('header.profile.show'), current_user, class: "dropdown-item" %></li>
          <li><%= link_to t('header.profile.edit'), edit_user_registration_path, class: "dropdown-item" %></li>
          <li><hr class="dropdown-divider"></li>
          <li><%= link_to t('header.profile.log_out'), destroy_user_session_path, class: "dropdown-item" %></li>
        </ul>
      <% else %>
        <span class="nav-item">
          <%= link_to t('header.log_in'), new_user_session_path, class: "nav-link text-secondary" %>
        </span> 
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DotfileSharingService</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
  </body>
</html>